[package]
name = "fake"
version = "0.1.0"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "A library for generating fake data in Rust."
keywords = ["faker", "data", "generator"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cksac/fake-rs"
homepage = "https://github.com/cksac/fake-rs"

[dependencies]
rand = "0.3.14"
clippy = {version = "*", optional = true}

[features]
default = []
dev = ["clippy"]