[package]
name = "dummy"
version = "0.3.0"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "Macros implementation of #[derive(Dummy)]"
keywords = ["faker", "data", "random"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/cksac/faker-rs/dummy_derive"
homepage = "https://github.com/cksac/faker-rs/dummy_derive"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.26"
quote = "0.6"
darling = "0.9.0"

[dev-dependencies]
fake = { version = "2.0", path = "../fake", features=['derive']}
rand="0.7"