[package]
name = "fake"
version = "2.1.0"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "An easy to use library for generating fake data like name, number, address, lorem, dates, etc."
keywords = ["faker", "data", "generator", "random"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/cksac/fake-rs/fake"
homepage = "https://github.com/cksac/fake-rs/fake"
edition = "2018"

[dependencies]
dummy = { version = "0.3", optional = true, path = "../dummy_derive" }
rand = "0.7"
chrono = { version = "0.4", optional = true }
http = { version = "0.1", optional = true }

[features]
wasm-bindgen = ["rand/wasm-bindgen"]

# Provide derive(Dummy) macros.
derive = ["dummy"]